name: Update gist with WakaTime stats
on:
  push:
    branches: master
    
  schedule:
    - cron: "* * * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js  --unhandled-rejections=strict
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ac47b9d6356c9ece1b3f9ddbbed41881
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
